//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamWorkerStudioJobs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamWorkerStudioJobs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProjectList&gt;
        ///  &lt;Project ID=&quot;Software&quot; Name=&quot;应用程序和游戏开发项目&quot; Introduction=&quot;开发应用程序和游戏，学习计算机科学和软件工程相关技术。&quot;&gt;
        ///    &lt;Job ID=&quot;Developer&quot; Name=&quot;程序开发工程师&quot; Introduction=&quot;使用 C#，在 Windows 平台使用 Visual Studio 开发卓越的通用应用程序。&quot; Requirement=&quot;你需要具有开发 Windows 应用程序的经验，当然，我们希望的更多是学习和团队合作的能力，如果你有 Linux, Android, IOS, Mac OS X 的开发经验的话，我们也欢迎你们的加入。&quot;/&gt;
        ///    &lt;Job ID=&quot;Tester&quot; Name=&quot;测试工程师&quot; Introduction=&quot;与程序开发工程师协同工作，进行代码审查，编写单元测试和UI测试，测试应用程序和游戏，保证产品代码的质量。&quot; Requirement=&quot;你需要具有软件开发和测试的经验，在各种设备上测试应用程序并发现问 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
    }
}
